# Generated by Django 4.2.6 on 2023-10-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlane', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airlane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airlane.airlane'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
