# Generated by Django 4.2.6 on 2023-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('planes', models.ManyToManyField(to='plane.plane')),
            ],
        ),
    ]
